# Generated by Django 5.2.12 on 2026-03-24 16:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workspacemember',
            unique_together={('user', 'workspace')},
        ),
    ]
